### ISSUE TITLE
error installing app center analytics

### ISSUE THREAD

**Issue by jamesdixon** [Microsoft/appcenter-sdk-cordova#72]
### **Description**

Hi, I'm attempting to install App Center Analytics and receiving the following error:

```
$ cordova plugin add cordova-plugin-appcenter-analytics
Installing "cordova-plugin-appcenter-analytics" for android
Installing "cordova-plugin-appcenter-shared" for android
Android Studio project detected
Failed to install 'cordova-plugin-appcenter-shared': Error: Unquoted attribute value
Line: 1
Column: 31
Char: f
    at error (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:347:8)
    at strictFail (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:364:22)
    at SAXParser.write (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:913:11)
    at XMLParser.feed (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/elementtree.js:271:10)
    at Object.exports.XML (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/elementtree.js:606:13)
    at Object.parseElementtreeSync (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:185:38)
    at new AndroidManifest (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/Api.js:223:57)
Failed to install 'cordova-plugin-appcenter-analytics': Error: Unquoted attribute value
Line: 1
Column: 31
Char: f
    at error (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:347:8)
    at strictFail (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:364:22)
odin:mobile-staff jamesdixon$ cordova plugin add cordova-plugin-appcenter-analytics
Installing "cordova-plugin-appcenter-analytics" for android
Installing "cordova-plugin-appcenter-shared" for android
Android Studio project detected
Failed to install 'cordova-plugin-appcenter-shared': Error: Unquoted attribute value
Line: 1
Column: 31
Char: f
    at error (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:347:8)
    at strictFail (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:364:22)
    at SAXParser.write (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:913:11)
    at XMLParser.feed (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/elementtree.js:271:10)
    at Object.exports.XML (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/elementtree.js:606:13)
    at Object.parseElementtreeSync (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:185:38)
    at new AndroidManifest (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/Api.js:223:57)
Failed to install 'cordova-plugin-appcenter-analytics': Error: Unquoted attribute value
Line: 1
Column: 31
Char: f
    at error (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:347:8)
    at strictFail (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:364:22)
    at SAXParser.write (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/sax/lib/sax.js:913:11)
    at XMLParser.feed (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/elementtree.js:271:10)
    at Object.exports.XML (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/elementtree/lib/elementtree.js:606:13)
    at Object.parseElementtreeSync (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:185:38)
    at new AndroidManifest (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/jamesdixon/Projects/scout/platform/mobile-staff/platforms/android/cordova/Api.js:223:57)
Unquoted attribute value
Line: 1
Column: 31
Char: f
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

I simply ran `cordova plugin add cordova-plugin-appcenter-analytics`

### **Details**

1. Which SDK version are you using?
Attempting to install v0.3.0 of the plugin

3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
cordova: 8.1.2 (cordova-lib@8.1.1)
cordova-ios: 4.5.4
cordova-android: 7.1.0
cocoapods: 1.5.3
ruby: 2.3.7p456
node: 8.12

5. What third party plugins are you using?
```
com-badrit-base64 0.2.0 "Base64"
com-sarriaroman-photoviewer 1.1.18 "PhotoViewer"
cordova-android-support-gradle-release 1.4.5 "cordova-android-support-gradle-release"
cordova-background-geolocation 2.14.5 "BackgroundGeolocation"
cordova-background-geolocation-lt 2.14.0 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appcenter-analytics 0.3.0 "App Center Analytics for Cordova"
cordova-plugin-appcenter-shared 0.3.0 "App Center shared code for Cordova"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-camera 4.0.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-fingerprint-aio 1.3.8 "FingerprintAllInOne"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-hockeyapp 5.1.2 "HockeyApp"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-taptic-engine 2.1.0 "Taptic Engine"
cordova-plugin-telerik-imagepicker 2.2.3 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.5.1 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"
```

Thanks!

**Comment by jamesdixon** [comment]
Sorry - turns out it was an issue in my AndroidManifest!

**Comment by serkon** [comment]
I am getting this errors on terminal while installing cordova appcenter plugin
command:  `cordova plugin add cordova-plugin-appcenter-analytics`

ERRORS:

```bash
$ cordova plugin add cordova-plugin-appcenter-analytics
Installing "cordova-plugin-appcenter-analytics" for android
Installing "cordova-plugin-appcenter-shared" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-appcenter-analytics" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.3.0" already fetched, using that version.
Installing "cordova-plugin-appcenter-shared" for ios
Failed to install 'cordova-plugin-appcenter-shared': undefined
Failed to install 'cordova-plugin-appcenter-analytics': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```


Environment is:
```sh
$ ionic info

Ionic:

   ionic (Ionic CLI)             : 4.9.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 16 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 7.0.0
   NodeJS     : v11.8.0 (/usr/local/bin/node)
   npm        : 6.5.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61
```

**Comment by annakocheshkova** [comment]
@serkon please [open a new issue](https://github.com/Microsoft/appcenter-sdk-cordova/issues/new). Thanks!
