### ISSUE TITLE
cordova prepare fails on clean build folder

### ISSUE THREAD

**Issue by jacobg** [Microsoft/AppCenter-SDK-Cordova#83]
### **Description**

`cordova prepare` fails on a clean build folder with these error message:
```
Failed to install 'cordova-plugin-appcenter-shared': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/jacob/workspace/tc/src-cordova/node_modules/cordova-common/src/superspawn.js:125:23)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:988:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
Failed to install 'cordova-plugin-appcenter-analytics': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/jacob/workspace/tc/src-cordova/node_modules/cordova-common/src/superspawn.js:125:23)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:988:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
Failed to restore plugin "cordova-plugin-appcenter-analytics" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 31
```
```
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-appcenter-shared': CordovaError: Uh oh!
"/Users/jacob/workspace/tc/src-cordova/platforms/ios/F/Plugins/cordova-plugin-appcenter-shared/AppCenterShared.m" already exists!
    at copyNewFile (/Users/jacob/workspace/tc/src-cordova/platforms/ios/cordova/lib/plugman/pluginHandlers.js:337:45)
    at installHelper (/Users/jacob/workspace/tc/src-cordova/platforms/ios/cordova/lib/plugman/pluginHandlers.js:260:13)
    at install (/Users/jacob/workspace/tc/src-cordova/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
    at ActionStack.process (/Users/jacob/workspace/tc/src-cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/jacob/workspace/tc/src-cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/jacob/workspace/tc/src-cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/jacob/workspace/farlock-tc/src-cordova/platforms/ios/cordova/Api.js:247:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:854:54)
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Start with clean build folder
2. Run cordova prepare on existing project

To workaround this issue, I have to remove and re-add the appcenter plugins after cordova prepare.

### **Details**

1. Which SDK version are you using?
    - 0.3.3
2. Which OS version did you experience the issue on?
    - MacOS
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - Cordova 8.1.2, cordova-ios 5.0.0; cordova-android 8.0.0
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    - N/A
5. What third party plugins are you using?
```
code-push 2.0.6 "CodePushAcquisition"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-app-preferences 0.99.4 "AppPreferences"
cordova-plugin-appcenter-analytics 0.3.3 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.3.3 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.3.3 "App Center shared code for Cordova"
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase-dynamiclinks 1.0.1 "FirebaseDynamicLinksPlugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.1.0-dev "InAppBrowser"
cordova-plugin-nativegeocoder 3.2.1 "NativeGeocoder"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-evcore-extbuild-free 0.9.10 "Cordova sqlite storage - free enterprise version with Android performance/memory improvements and extra features for PhoneGap Build"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
```

**Comment by MatkovIvan** [comment]
Hi @jacobg,

Thanks for getting in touch! It looks very similar to already known issue. It was partially fixed in Cordova iOS 5.0, but this still has some problems.
Please check our [troubleshooting page](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/cordova#failed-to-install-plugin---pod-command-failed-with-exit-code-1) and [this thread](
https://github.com/apache/cordova-ios/issues/468#issuecomment-465346038).
Please let me know if that workaround doesn't work for you.

Thanks,
Ivan

**Comment by annakocheshkova** [comment]
Hi @jacobg, please tell us did you happen to resolve this issue?

**Comment by jacobg** [comment]
Umm.... I switched to Firebase.

If you're setting up a new build folder, you'll need to remove the appcenter plugins, run cordova prepare, and then re-add them.

**Comment by annakocheshkova** [comment]
Yes this is what has been suggested in this thread. Unfortunately, this is a cordova-ios bug. I'm closing this one.
