### ISSUE TITLE
Unable to install cordova-plugin-appcenter-shared - "framework" tag with type "podspec" is deprecated and will be removed

### ISSUE THREAD

**Issue by u01jmg3** [microsoft/AppCenter-SDK-Cordova#87]
### **Description**

On a Windows machine using the Cordova client I cannot install "cordova-plugin-appcenter-shared" for ios.

```
iOS project created with cordova-ios@5.0.1
Installing "cordova-plugin-appcenter-analytics" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.3.3" already fetched, using that version.
Installing "cordova-plugin-appcenter-shared" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
shell.js: internal error
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. `cordova platform add ios`

```
<plugin name="cordova-plugin-appcenter-analytics" spec="^0.3.3" />
<plugin name="cordova-plugin-appcenter-crashes" spec="^0.3.3" />
```

### **Details**

1. Which SDK version are you using?
    - `v0.3.3`
2. Which OS version did you experience the issue on?
    - N/A
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - Cordova `v9.0.0`
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    - N/A
5. What third party plugins are you using?

```
cordova-plugin-appcenter-analytics 0.3.3 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.3.3 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.3.3 "App Center shared code for Cordova"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-name 1.3.5 "Device-Name"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-itunesfilesharing 0.0.2 "cordova-plugin-itunesfilesharing"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-evcore-extbuild-free 0.9.10 "Cordova sqlite storage - free enterprise version with Android performance/memory improvements and extra features for PhoneGap Build"
```

**Comment by AnastasiaKubova** [comment]
Hi, @u01jmg3! Thank for contacting! Unfortunately, I can't reproduce this error. How often does this error appear?  Can you please run this with verbose logs `cordova platform add ios --verbose` and send us the result?

**Comment by u01jmg3** [comment]
Thanks for the quick reply.

```
C:\Assess>cordova platform add ios --verbose
No scripts found for hook "before_platform_add".
No version supplied. Retrieving version from config.xml...
Using cordova-fetch for cordova-ios@^5.0.1
saving
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-ios@^5.0.1 --production --save""
Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-ios@^5.0.1 --production --save"
Removing "cordova-" prefix from cordova-ios
Adding ios project...
PlatformApi successfully found for platform ios
Creating Cordova project for the iOS platform:
        Path: platforms\ios
        Package: com.medical.assessmentcentral
        Name: Assess
Copying iOS template project to C:\Assess\platforms\ios
iOS project created with cordova-ios@5.0.1
Checking for any plugins added to the project that have not been installed in ios platform
No differences found between plugins added to project and installed in ios platform. Continuing...
PlatformApi successfully found for platform ios
Generating platform-specific config.xml from defaults for iOS at C:\Assess\platforms\ios\Assess\config.xml
Merging project's config.xml into platform-specific iOS config.xml
Merging and updating files from [www, platforms\ios\platform_www] to platforms\ios\www
  mkdir platforms\ios\www\cordova-js-src
  copy  platforms\ios\platform_www\cordova-js-src\exec.js platforms\ios\www\cordova-js-src\exec.js (new file)
  copy  platforms\ios\platform_www\cordova-js-src\platform.js platforms\ios\www\cordova-js-src\platform.js (new file)
  mkdir platforms\ios\www\cordova-js-src\plugin
  mkdir platforms\ios\www\cordova-js-src\plugin\ios
  copy  platforms\ios\platform_www\cordova-js-src\plugin\ios\console.js platforms\ios\www\cordova-js-src\plugin\ios\console.js (new file)
  copy  platforms\ios\platform_www\cordova-js-src\plugin\ios\logger.js platforms\ios\www\cordova-js-src\plugin\ios\logger.js (new file)
  copy  platforms\ios\platform_www\cordova.js platforms\ios\www\cordova.js (updated file)
  copy  www\index.html platforms\ios\www\index.html (updated file)
  copy  www\js\index.js platforms\ios\www\js\index.js (updated file)
Current launch storyboard undefined
Not changing launch storyboard setting in info plist.
Wrote out iOS Bundle Version "1.0.0" to C:\Assess\platforms\ios\Assess\Assess-Info.plist
Need to update build settings because project is using legacy launch images and no storyboard.
Set PRODUCT_BUNDLE_IDENTIFIER to com.medical.assessmentcentral.
Set ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME to LaunchImage because project is using legacy launch images and no storyboard.
iOS Product Name has not changed (still "Assess")
Updating icons at platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\
  copy  res/icon/ios/iTunesArtwork@2x.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-1024.png (updated file)
  copy  res/icon/ios/icon-40.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-20@2x.png (updated file)
  copy  res/icon/ios/icon-small.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-29.png (updated file)
  copy  res/icon/ios/icon-small@2x.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-29@2x.png (updated file)
  copy  res/icon/ios/icon-small@3x.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-29@3x.png (updated file)
  copy  res/icon/ios/icon-40.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-40.png (updated file)
  copy  res/icon/ios/icon-40@2x.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-40@2x.png (updated file)
  copy  res/icon/ios/icon-40@3x.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-60@2x.png (updated file)
  copy  res/icon/ios/icon-72.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-72.png (updated file)
  copy  res/icon/ios/icon-72@2x.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon-72@2x.png (updated file)
  copy  res/icon/ios/icon-57.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon.png (updated file)
  copy  res/icon/ios/icon-57@2x.png platforms\ios\Assess\Images.xcassets\AppIcon.appiconset\icon@2x.png (updated file)
Updating splash screens at platforms\ios\Assess\Images.xcassets\LaunchImage.launchimage\
  copy  res/screen/ios/screen-iphone-portrait-568h@2x.png platforms\ios\Assess\Images.xcassets\LaunchImage.launchimage\Default-568h@2x~iphone.png (updated file)
  copy  res/screen/ios/screen-ipad-landscape@2x.png platforms\ios\Assess\Images.xcassets\LaunchImage.launchimage\Default-Landscape@2x~ipad.png (updated file)
  copy  res/screen/ios/screen-ipad-landscape.png platforms\ios\Assess\Images.xcassets\LaunchImage.launchimage\Default-Landscape~ipad.png (updated file)
  copy  res/screen/ios/screen-ipad-portrait@2x.png platforms\ios\Assess\Images.xcassets\LaunchImage.launchimage\Default-Portrait@2x~ipad.png (updated file)
  copy  res/screen/ios/screen-ipad-portrait.png platforms\ios\Assess\Images.xcassets\LaunchImage.launchimage\Default-Portrait~ipad.png (updated file)
  copy  res/screen/ios/screen-iphone-portrait@2x.png platforms\ios\Assess\Images.xcassets\LaunchImage.launchimage\Default@2x~iphone.png (updated file)
  copy  res/screen/ios/screen-iphone-portrait.png platforms\ios\Assess\Images.xcassets\LaunchImage.launchimage\Default~iphone.png (updated file)
Updating launch storyboard images at platforms\ios\Assess\Images.xcassets\LaunchStoryboard.imageset\
Updating Storyboard image set contents.json
This app does not have additional resource files defined
Prepared iOS project successfully
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are different. Updating package.json with most current list of platforms.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
Checking config.xml for saved plugins that haven't been added to the project
Discovered plugin "cordova-plugin-appcenter-analytics" in config.xml. Adding it to the project
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "cordova-plugin-appcenter-analytics@^0.3.3"
saving
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-plugin-appcenter-analytics@"^0.3.3" --production --save""
Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-plugin-appcenter-analytics@"^0.3.3" --production --save"
Copying plugin "C:\Assess\node_modules\cordova-plugin-appcenter-analytics" => "C:\Assess\plugins\cordova-plugin-appcenter-analytics"
Calling plugman.install on plugin "C:\Assess\plugins\cordova-plugin-appcenter-analytics" for platform "ios
Installing "cordova-plugin-appcenter-analytics" for ios
Running command: cmd "/s /c ""C:\Assess\platforms\ios\cordova\version.bat"""
Command finished with error code 0: cmd /s /c ""C:\Assess\platforms\ios\cordova\version.bat""
Dependencies detected, iterating through them...
Requesting plugin "cordova-plugin-appcenter-shared@0.3.3".
Plugin dependency "cordova-plugin-appcenter-shared" not fetched, retrieving then installing.
saving
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-plugin-appcenter-shared@0.3.3 --production --save""
Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-plugin-appcenter-shared@0.3.3 --production --save"
Copying plugin "C:\Assess\node_modules\cordova-plugin-appcenter-shared" => "C:\Assess\plugins\cordova-plugin-appcenter-shared"
Installing "cordova-plugin-appcenter-shared" for ios
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-appcenter-shared on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-appcenter-shared" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
pods.json: The file at C:\Assess\platforms\ios\pods.json does not exist.
Creating new pods.json in platforms/ios
Wrote to pods.json.
Podfile: The file at C:\Assess\platforms\ios\Podfile does not exist.
Creating new Podfile in platforms/ios
Wrote to Podfile.
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Adding pods since the plugin contained <framework>(s) with type="podspec"
Set pods.json for `libraries` - `AppCenter`
Added pod line for `AppCenter`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
shell.js: internal error
Error: Command failed: "C:\Program Files\nodejs\node.exe" C:\Users\J. Goode\AppData\Local\Temp\shelljs_98b7d4274051375c080c
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at execSync (C:\Assess\node_modules\shelljs\src\exec.js:81:11)
    at Object._exec (C:\Assess\node_modules\shelljs\src\exec.js:214:12)
    at Object.exec (C:\Assess\node_modules\shelljs\src\common.js:182:23)
    at C:\Assess\platforms\ios\cordova\lib\check_reqs.js:124:30
    at _fulfilled (C:\Assess\node_modules\q\q.js:854:54)
    at C:\Assess\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Assess\node_modules\q\q.js:816:13)
    at C:\Assess\node_modules\q\q.js:877:14
```

**Comment by carlrabbit** [comment]
Had the same problem. Running `pod repo update` seems to have fixed the problems. Not sure if the real error was swallowed somewhere else?

**Comment by u01jmg3** [comment]
Should I have installed [pod](https://www.npmjs.com/package/pod)?

**Comment by carlrabbit** [comment]
Nope. pod is a package manager. It should be installed. See https://cocoapods.org/

**Comment by u01jmg3** [comment]
But I am on Windows...

**Comment by AnastasiaKubova** [comment]
If you want to build your app for iOS you'll need a Mac with xcode and Cordova installed. Or you could use a virtual machine to do it.

**Comment by u01jmg3** [comment]
I have been using PhoneGap Build to build my Cordova/PhoneGap app for iOS which negates the need for requiring a Mac.

I was hoping to integrate `cordova-plugin-appcenter-analytics` and `cordova-plugin-appcenter-crashes` into my existing app but am failing at the installation stage.

**Comment by AnastasiaKubova** [comment]
Please try download from here: https://rubyinstaller.org/
Then you can use `gem` to run ruby-cli command, therefore you can run `gem install cocoapods`.

**Comment by annakocheshkova** [comment]
Hi @u01jmg3 we haven't heard from you in a while. If you have any updates, feel free to re-open this issue!

**Comment by u01jmg3** [comment]
I have done as suggested and installed Ruby and then ran `gem install cocoapods` which completed successfully.

However, the issue remains.

```
C:\Assess>cordova platform add ios
Using cordova-fetch for cordova-ios@^5.0.1
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms\ios
        Package: com.medical.assessmentcentral
        Name: Assess
iOS project created with cordova-ios@5.0.1
Installing "cordova-plugin-appcenter-analytics" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.3.4" already fetched, using that version.
Installing "cordova-plugin-appcenter-shared" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
shell.js: internal error
```

**Comment by annakocheshkova** [comment]
Please go under **platforms** > **ios** and run `pod install` then send us the logs. Thank you!

**Comment by u01jmg3** [comment]
Ran into these two issues along the way because I am on Windows:

1. [Cannot run CocoaPods as root](https://stackoverflow.com/questions/23190064/cant-run-sudo-pod-install-after-updating-to-cocoapods-0-32-1-with-error-you-ca#answer-37451422)
2. [Unable to locate the executable `git`](https://stackoverflow.com/questions/18355710/cocoapods-unable-to-locate-the-executable-git#answer-53204534)

Hit this error:

```
C:\Assess\platforms\ios>pod install
Analyzing dependencies

MARKDOWN TEMPLATE

### Command

C:/Ruby/bin/pod install

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

   CocoaPods : 1.6.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
    RubyGems : 3.0.3
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : -version) ()
         Git : git version 2.21.0.windows.1
Ruby lib dir : C:/Ruby/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d8ed9f831cb32770208dd4ea5a534da3b1d1cb3e

### Plugins

cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0

### Podfile

# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '9.0'

target 'Assess' do
	    project 'C:\Assess\platforms\ios\Assess.xcodeproj'        
        pod 'AppCenter', '~> 2.0.1'
end

### Error

Errno::ENOENT - No such file or directory - env -u GIT_CONFIG git -C "C:/Users/Username/.cocoapods/repos/master" config --get remote.origin.url
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source.rb:448:in '
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source.rb:448:in repo_git'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source.rb:46:in url'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source/manager.rb:347:in block in source_with_url'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source/manager.rb:346:in each'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source/manager.rb:346:in find'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source/manager.rb:346:in source_with_url'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/sources_manager.rb:18:in find_or_create_source_with_url'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:169:in block in sources'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:168:in map'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:168:in sources'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:908:in block in resolve_dependencies'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in section'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in resolve_dependencies'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in analyze'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in analyze'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in block in resolve_dependencies'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in section'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in resolve_dependencies'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in install!'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in run'
C:/Ruby/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in run'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in run'
C:/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/bin/pod:55:in <top (required)>'
C:/Ruby/bin/pod:23:in load'
C:/Ruby/bin/pod:23:in <main>'

TEMPLATE END

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+-+env+-u+GIT_CONFIG+git+-C+%22C%3A%2FUsers%2FUsername%2F.cocoapods%2Frepos%2Fmaster%22+config+--get+remote.origin.url&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
```

**Comment by annakocheshkova** [comment]
@u01jmg3 looks like this is not our SDK problem: a problem is with cocoapods running on Windows machine. Are you sure that's even possible?
Anyway, I can give you the instructions on how to integrate the SDK without **cocoapods**, similar to [React Native ones](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#33-ios-only-integrate-the-ios-sdk-manually-without-react-native-link-or-cocoapods), but I'm not sure it will even build, tbh.

**Comment by u01jmg3** [comment]
Okay - should it be made clearer that your Cordova plugins cannot be installed using a Windows machine unlike other Cordova plugins?

**Comment by annakocheshkova** [comment]
@u01jmg3 we have **CocoaPods** in the prerequisites: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/cordova#1-prerequisites
But we didn't add any notes on whether **CocoaPods** is compatible with Windows. For this you should refer to Cocoapods documentation, not ours.

**Comment by annakocheshkova** [comment]
Do you need to me to guide you through the manual SDK integration?

**Comment by u01jmg3** [comment]
> _But we didn't add any notes on whether CocoaPods is compatible with Windows._
>
> _For this you should refer to Cocoapods documentation, not ours._

Your documentation is still misleading though when you state: `Start by opening a Terminal window or **Windows command prompt**...` when it is not possible to install one of your prerequisites on a Windows machine.

> _Do you need to me to guide you through the manual SDK integration?_

Unfortunately I am going to stop here. When I first started I thought it would just be a case of installing a Cordova plugin like any other. I do appreciate all your time/help though.

**Comment by annakocheshkova** [comment]
@u01jmg3 sorry to hear that. 
> Start by opening a Terminal window or **Windows command prompt**...
refers to macOS/Windows, because it's still possible to develop on windows for Android.

**Comment by u01jmg3** [comment]
> _Refers to MacOS/Windows, because it's still possible to develop on Windows for Android._

Fair enough. Hopefully anybody else like me will stumble across this issue.
